### ISSUE TITLE
insert multiple values in one statement does not work in PostgreSQL

### ISSUE THREAD

**Issue by lindsejs** [mrumkovskis/Query#15]
Query:

DEPT {DEPTNO, DNAME, LOC} + [10, "ACCOUNTING", "NEW YORK"], [20, "RESEARCH", "DALLAS"] 

compiles to:

insert into DEPT (DEPTNO, DNAME, LOC) values ((10, 'ACCOUNTING', 'NEW YORK'),(20, 'RESEARCH', 'DALLAS'))

but double brackets does not work in PostgreSQL, should be:

insert into DEPT (DEPTNO, DNAME, LOC) values (10, 'ACCOUNTING', 'NEW YORK'),(20, 'RESEARCH', 'DALLAS')

**Comment by mrumkovskis** [comment]
Resolved in commit c492bc1e46c97580443e0c6485ddeb699223cb65.
